utils::update.packages(ask = TRUE, dependencies = c('Suggests'), repos='https://cloud.r-project.org/')

library(lazyeval)
library(plyr)
library(dplyr)
library(devtools)
library(formattable)
library(magrittr)
library(tidyr)
library(stringr)
library(tibble)
library(reshape)
library(reshape2)
library(R.utils)
# install_github("Katiedaisey/ggplot2")
# install.packages("ggplot2")
library(ggplot2)
library(broom)
# library(effects)
library(knitr)
library(rmarkdown)
library(roxygen2)
library(pryr)
library(readr)

#devtools::install_github("darrellpenta/dissertate", force = TRUE)
library(dissertate)
# library(APAstyler)


# install.packages("tidyverse")
# library(tidyverse)
