# utils::update.packages(ask = FALSE, dependencies = c('Suggests'), repos='https://cloud.r-project.org/')
library(stats)
library(lazyeval)
library(plyr)
library(dplyr)
library(devtools)
library(formattable)
library(magrittr)
library(tidyr)
library(stringr)
library(tibble)
library(reshape)
library(reshape2)
library(R.utils)
# install_github("Katiedaisey/ggplot2")
library(ggplot2)
library(broom)
library(broom)
library(effects)
library(knitr)
library(rmarkdown)
library(bookdown)
library(thesisdown)
#devtools::install_github("darrellpenta/dissertate", force = TRUE)
# library(dissertate)
# library(APAstyler)


# install.packages("tidyverse")
# library(tidyverse)
