#' Compute a standard error statistic for a vector

#' @param data a \code{factor.grid} dataframe generated by \code{\link{factor_grid}} or \code{\link{df_to_factgrid}}
#' @return a standard error
#' @export
#'


standard_error <- function(data){

    data <-
      stats::sd(data) / sqrt(length(data))

}
